---
name: Build and React App to S3 Bucket
on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      # React App/Build Settings
      DIST: build
      SKIP_PREFLIGHT_CHECK: true
      REACT_APP_BASE_URL: ${{ secrets.REACT_APP_BASE_URL }}
      REACT_APP_SOCKET_PATH: ${{ secrets.REACT_APP_SOCKET_PATH }}
      REACT_APP_AVATAR_API: ${{ secrets.REACT_APP_AVATAR_API }}
      # AWS Settings
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Dependencies
        run: |
          node --version
          npm install --global yarn
          yarn install

      - name: Build Static Website
        run: yarn build

      - name: Copy files to the S3 Bucket with the AWS CLI
        run: |
          aws s3 sync --delete ${{ env.DIST }} s3://${{ env.AWS_S3_BUCKET }}
